### ISSUE TITLE
(Easy) Possibility of double setting of access token cookie

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-go#4]
We need to make sure that the [`setCookie`](https://supertokens.io/discord) function in [cookieAndHeaders.go](https://github.com/supertokens/supertokens-go/blob/master/supertokens/cookieAndHeaders.go#L101), if given the same cookie twice, does not set it two times. Instead, the older cookie should be overwritten by the new cookie. 

For example, if I call `setCookie` with a cookie like `abc=someVal`, and then I call it again with a cookie like `abc=someOtherVal`, the final response should have just `Set-Cookie: abc=someOtherVal` and not `Set-Cookie: abc=someOtherVal; abc=someVal`

**Comment by kamil200** [comment]
Hi, I wanted to contribute in this project. Can anyone guide me how to work on this project?

**Comment by rishabhpoddar** [comment]
Hi @kamil200 . I have assigned this issue to you. You can read the `CONTRIBUTING.md` file in this repo to setup the dev env. More details about this issue can be found in the first comment.

**Comment by metallicmonkey** [comment]
Hi there! could you assign this issue to me please? I think I have an easy way to solve that.

**Comment by rishabhpoddar** [comment]
@metallicmonkey sure! Done.

**Comment by metallicmonkey** [comment]
Thanks! I'm afraid I don't have the correct access rights to the repo though :(

**Comment by rishabhpoddar** [comment]
You can fork the `supertokens-go` repo to make your changes and then issue a pull request. If you want to setup the full dev environment, then you can also clone the `supertokens-core` repo - it's open source :)

**Comment by metallicmonkey** [comment]
done :)
